#include <stdlib.h>
#include <opcode_init.h>


void set_opcode(struct opcode** opcode_ptr, unsigned char opcode, char* name, opcode_action action, unsigned char address_mode, unsigned char cycles)
{
  (*opcode_ptr)[opcode].name = name;
  (*opcode_ptr)[opcode].action = action;
  (*opcode_ptr)[opcode].address_mode = address_mode;
  (*opcode_ptr)[opcode].cycles = cycles;
}
void set_opcodes(struct opcode** opcodes_ptr, struct address** addresses_ptr)
{
  (*opcodes_ptr) = malloc(256 * sizeof(struct opcode));
  (*addresses_ptr) = malloc(15 * sizeof(struct address));
  unsigned char IMMEDIATE_ADDRESS_MODE = 0;
  unsigned char ZEROPAGE_ADDRESS_MODE = 1;
  unsigned char ACCUMULATOR_ADDRESS_MODE = 2;
  unsigned char ABSOLUTE_ADDRESS_MODE = 3;
  unsigned char ZEROPAGE_X_ADDRESS_MODE = 4;
  unsigned char ABSOLUTE_X_ADDRESS_MODE = 5;
  unsigned char INDEXED_INDIRECT_X_ADDRESS_MODE = 6;
  unsigned char INDIRECT_INDEXED_Y_ADDRESS_MODE = 7; 
  unsigned char ABSOLUTE_Y_ADDRESS_MODE = 8;
  unsigned char ZEROPAGE_Y_ADDRESS_MODE = 9;
  unsigned char NONE_ADDRESS_MODE = 10;
  unsigned char ABSOLUTE_INDIRECT_ADDRESS_MODE = 11;
  unsigned char BRANCH_DUMMY = 12;
  unsigned char JUMP_DUMMY = 13;
  unsigned char JSR_DUMMY = 14;
  
  (*addresses_ptr)[0].program_counter_increment = 2;
  (*addresses_ptr)[0].get_operand_ptr = get_immediate_operand_ptr;
  (*addresses_ptr)[0].address_info = "#$%02X";
  (*addresses_ptr)[0].inc_pc = 1;

  (*addresses_ptr)[1].program_counter_increment = 2;
  (*addresses_ptr)[1].get_operand_ptr = get_zeropage_operand_ptr;
  (*addresses_ptr)[1].address_info = "$%02X";
  (*addresses_ptr)[1].inc_pc = 1;
 
  (*addresses_ptr)[2].program_counter_increment = 1;
  (*addresses_ptr)[2].get_operand_ptr = get_accumulator_operand_ptr;
  (*addresses_ptr)[2].address_info = "A";
  (*addresses_ptr)[2].inc_pc = 1;

  (*addresses_ptr)[3].program_counter_increment = 3;
  (*addresses_ptr)[3].get_operand_ptr = get_absolute_operand_ptr;
  (*addresses_ptr)[3].address_info = "$%02X%02X";
  (*addresses_ptr)[3].inc_pc = 1;
 
  (*addresses_ptr)[4].program_counter_increment = 2;
  (*addresses_ptr)[4].get_operand_ptr = get_zeropage_X_operand_ptr;
  (*addresses_ptr)[4].address_info = "$%02X,X";
  (*addresses_ptr)[4].inc_pc = 1;

  (*addresses_ptr)[5].program_counter_increment = 3;
  (*addresses_ptr)[5].get_operand_ptr = get_absolute_X_operand_ptr;
  (*addresses_ptr)[5].address_info = "$%02X%02X,X";
  (*addresses_ptr)[5].inc_pc = 1;

  (*addresses_ptr)[6].program_counter_increment = 2;
  (*addresses_ptr)[6].get_operand_ptr = get_indexed_indirect_X_operand_ptr;
  (*addresses_ptr)[6].address_info = "($%02X,X)";
  (*addresses_ptr)[6].inc_pc = 1;

  (*addresses_ptr)[7].program_counter_increment = 2;
  (*addresses_ptr)[7].get_operand_ptr = get_indirect_indexed_Y_operand_ptr;
  (*addresses_ptr)[7].address_info = "($%02X),Y";
  (*addresses_ptr)[7].inc_pc = 1;

  (*addresses_ptr)[8].program_counter_increment = 3;
  (*addresses_ptr)[8].get_operand_ptr = get_absolute_Y_operand_ptr;
  (*addresses_ptr)[8].address_info = "$%02X%02X,Y";
  (*addresses_ptr)[8].inc_pc = 1;

  (*addresses_ptr)[9].program_counter_increment = 2;
  (*addresses_ptr)[9].get_operand_ptr = get_zeropage_Y_operand_ptr;
  (*addresses_ptr)[9].address_info = "$%02X,Y";
  (*addresses_ptr)[9].inc_pc = 1;

  (*addresses_ptr)[10].program_counter_increment = 1;
  (*addresses_ptr)[10].get_operand_ptr = get_dummy_operand_ptr;
  (*addresses_ptr)[10].address_info = "";
  (*addresses_ptr)[10].inc_pc = 1;

  (*addresses_ptr)[11].program_counter_increment = 3;
  (*addresses_ptr)[11].get_operand_ptr = get_absolute_indirect_operand_ptr;
  (*addresses_ptr)[11].address_info = "($%02X%02X)";
  (*addresses_ptr)[11].inc_pc = 0;

  (*addresses_ptr)[12].program_counter_increment = 3;
  (*addresses_ptr)[12].get_operand_ptr = get_branch_operand_ptr;
  (*addresses_ptr)[12].address_info = "$%04X";
  (*addresses_ptr)[12].inc_pc = 0;
 
  (*addresses_ptr)[13].program_counter_increment = 3;
  (*addresses_ptr)[13].get_operand_ptr = get_absolute_operand_ptr;
  (*addresses_ptr)[13].address_info = "$%02X%02X";
  (*addresses_ptr)[13].inc_pc = 0;

  (*addresses_ptr)[14].program_counter_increment = 1;
  (*addresses_ptr)[14].get_operand_ptr = get_absolute_operand_ptr;
  (*addresses_ptr)[14].address_info = "";
  (*addresses_ptr)[14].inc_pc = 0;

  for(int i=0; i<256; i++)
  {
    (*opcodes_ptr)[i].name = 0;
    (*opcodes_ptr)[i].action = 0;
  }

  set_opcode(opcodes_ptr, 0x00, "BRK", BRK, NONE_ADDRESS_MODE,7);
  set_opcode(opcodes_ptr, 0x01, "ORA", ORA_ptr, INDEXED_INDIRECT_X_ADDRESS_MODE,6);
  set_opcode(opcodes_ptr, 0x02, "STP", STP, NONE_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0x03, "SLO", SLO, INDEXED_INDIRECT_X_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0x04, "NOP", NOP, ZEROPAGE_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0x05, "ORA", ORA_ptr, ZEROPAGE_ADDRESS_MODE, 3);
  set_opcode(opcodes_ptr, 0x06, "ASL", ASL, ZEROPAGE_ADDRESS_MODE, 5);
  set_opcode(opcodes_ptr, 0x07, "SLO", SLO, ZEROPAGE_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0x08, "PHP", PHP, NONE_ADDRESS_MODE, 3);
  set_opcode(opcodes_ptr, 0x09, "ORA", ORA_ptr, IMMEDIATE_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0x0a, "ASL", ASL, ACCUMULATOR_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0x0b, "ANC", ANC, IMMEDIATE_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0x0c, "NOP", NOP, ABSOLUTE_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0x0d, "ORA", ORA_ptr, ABSOLUTE_ADDRESS_MODE, 4);
  set_opcode(opcodes_ptr, 0x0e, "ASL", ASL, ABSOLUTE_ADDRESS_MODE, 6);
  set_opcode(opcodes_ptr, 0x0f, "SLO", SLO, ABSOLUTE_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0x10, "BPL", BPL, BRANCH_DUMMY, 2);
  set_opcode(opcodes_ptr, 0x11, "ORA", ORA_ptr, INDIRECT_INDEXED_Y_ADDRESS_MODE, 5);
  set_opcode(opcodes_ptr, 0x12, "STP", STP, NONE_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0x13, "SLO", SLO, INDIRECT_INDEXED_Y_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0x14, "NOP", NOP, ZEROPAGE_X_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0x15, "ORA", ORA_ptr, ZEROPAGE_X_ADDRESS_MODE, 4);
  set_opcode(opcodes_ptr, 0x16, "ASL", ASL, ZEROPAGE_X_ADDRESS_MODE, 6);
  set_opcode(opcodes_ptr, 0x17, "SLO", SLO, ZEROPAGE_X_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0x18, "CLC", CLC, NONE_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0x19, "ORA", ORA_ptr, ABSOLUTE_Y_ADDRESS_MODE, 4);
  set_opcode(opcodes_ptr, 0x1a, "NOP", NOP, NONE_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0x1b, "SLO", SLO, ABSOLUTE_Y_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0x1c, "NOP", NOP, ABSOLUTE_X_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0x1d, "ORA", ORA_ptr, ABSOLUTE_X_ADDRESS_MODE, 4);
  set_opcode(opcodes_ptr, 0x1e, "ASL", ASL, ABSOLUTE_X_ADDRESS_MODE, 7);
  set_opcode(opcodes_ptr, 0x1f, "SLO", SLO, ABSOLUTE_X_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0x20, "JSR", JSR, JUMP_DUMMY, 6);
  set_opcode(opcodes_ptr, 0x21, "AND", AND_ptr, INDEXED_INDIRECT_X_ADDRESS_MODE, 6);
  set_opcode(opcodes_ptr, 0x22, "STP", STP, NONE_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0x23, "RLA", RLA, INDEXED_INDIRECT_X_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0x24, "BIT", BIT, ZEROPAGE_ADDRESS_MODE, 3);
  set_opcode(opcodes_ptr, 0x25, "AND", AND_ptr, ZEROPAGE_ADDRESS_MODE, 3);
  set_opcode(opcodes_ptr, 0x26, "ROL", ROL, ZEROPAGE_ADDRESS_MODE, 5);
  set_opcode(opcodes_ptr, 0x27, "RLA", RLA, ZEROPAGE_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0x28, "PLP", PLP, NONE_ADDRESS_MODE, 4);
  set_opcode(opcodes_ptr, 0x29, "AND", AND_ptr, IMMEDIATE_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0x2a, "ROL", ROL, ACCUMULATOR_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0x2b, "ANC", ANC, IMMEDIATE_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0x2c, "BIT", BIT, ABSOLUTE_ADDRESS_MODE, 4);
  set_opcode(opcodes_ptr, 0x2d, "AND", AND_ptr, ABSOLUTE_ADDRESS_MODE, 4);
  set_opcode(opcodes_ptr, 0x2e, "ROL", ROL, ABSOLUTE_ADDRESS_MODE, 6);
  set_opcode(opcodes_ptr, 0x2f, "RLA", RLA, ABSOLUTE_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0x30, "BMI", BMI, BRANCH_DUMMY, 2);
  set_opcode(opcodes_ptr, 0x31, "AND", AND_ptr, INDIRECT_INDEXED_Y_ADDRESS_MODE, 5);
  set_opcode(opcodes_ptr, 0x32, "STP", STP, NONE_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0x33, "RLA", RLA, INDIRECT_INDEXED_Y_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0x34, "NOP", NOP, ZEROPAGE_X_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0x35, "AND", AND_ptr, ZEROPAGE_X_ADDRESS_MODE, 4);
  set_opcode(opcodes_ptr, 0x36, "ROL", ROL, ZEROPAGE_X_ADDRESS_MODE, 6);
  set_opcode(opcodes_ptr, 0x37, "RLA", RLA, ZEROPAGE_X_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0x38, "SEC", SEC, NONE_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0x39, "AND", AND_ptr, ABSOLUTE_Y_ADDRESS_MODE, 4);
  set_opcode(opcodes_ptr, 0x3a, "NOP", NOP, NONE_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0x3b, "RLA", RLA, ABSOLUTE_Y_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0x3c, "NOP", NOP, ABSOLUTE_X_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0x3d, "AND", AND_ptr, ABSOLUTE_X_ADDRESS_MODE, 4);
  set_opcode(opcodes_ptr, 0x3e, "ROL", ROL, ABSOLUTE_X_ADDRESS_MODE, 7);
  set_opcode(opcodes_ptr, 0x3f, "RLA", RLA, ABSOLUTE_X_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0x40, "RTI", RTI, JSR_DUMMY, 6);
  set_opcode(opcodes_ptr, 0x41, "EOR", EOR_ptr, INDEXED_INDIRECT_X_ADDRESS_MODE, 6);
  set_opcode(opcodes_ptr, 0x42, "STP", STP, NONE_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0x43, "SRE", SRE, INDEXED_INDIRECT_X_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0x44, "NOP", NOP, ZEROPAGE_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0x45, "EOR", EOR_ptr, ZEROPAGE_ADDRESS_MODE, 3);
  set_opcode(opcodes_ptr, 0x46, "LSR", LSR, ZEROPAGE_ADDRESS_MODE, 5);
  set_opcode(opcodes_ptr, 0x47, "SRE", SRE, ZEROPAGE_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0x48, "PHA", PHA, NONE_ADDRESS_MODE, 3);
  set_opcode(opcodes_ptr, 0x49, "EOR", EOR_ptr, IMMEDIATE_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0x4a, "LSR", LSR, ACCUMULATOR_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0x4b, "ALR", ALR, IMMEDIATE_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0x4c, "JMP", JMP, JUMP_DUMMY, 3);
  set_opcode(opcodes_ptr, 0x4d, "EOR", EOR_ptr, ABSOLUTE_ADDRESS_MODE, 4);
  set_opcode(opcodes_ptr, 0x4e, "LSR", LSR, ABSOLUTE_ADDRESS_MODE, 6);
  set_opcode(opcodes_ptr, 0x4f, "SRE", SRE, ABSOLUTE_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0x50, "BVC", BVC, BRANCH_DUMMY, 2);
  set_opcode(opcodes_ptr, 0x51, "EOR", EOR_ptr, INDIRECT_INDEXED_Y_ADDRESS_MODE, 5);
  set_opcode(opcodes_ptr, 0x52, "STP", STP, NONE_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0x53, "SRE", SRE, INDIRECT_INDEXED_Y_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0x54, "NOP", NOP, ZEROPAGE_X_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0x55, "EOR", EOR_ptr, ZEROPAGE_X_ADDRESS_MODE, 4);
  set_opcode(opcodes_ptr, 0x56, "LSR", LSR, ZEROPAGE_X_ADDRESS_MODE, 6);
  set_opcode(opcodes_ptr, 0x57, "SRE", SRE, ZEROPAGE_X_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0x58, "CLI", CLI, NONE_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0x59, "EOR", EOR_ptr, ABSOLUTE_Y_ADDRESS_MODE, 4);
  set_opcode(opcodes_ptr, 0x5a, "NOP", NOP, NONE_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0x5b, "SRE", SRE, ABSOLUTE_Y_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0x5c, "NOP", NOP, ABSOLUTE_X_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0x5d, "EOR", EOR_ptr, ABSOLUTE_X_ADDRESS_MODE, 4);
  set_opcode(opcodes_ptr, 0x5e, "LSR", LSR, ABSOLUTE_X_ADDRESS_MODE, 7);
  set_opcode(opcodes_ptr, 0x5f, "SRE", SRE, ABSOLUTE_X_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0x60, "RTS", RTS, JSR_DUMMY, 6);
  set_opcode(opcodes_ptr, 0x61, "ADC", ADC_ptr, INDEXED_INDIRECT_X_ADDRESS_MODE, 6);
  set_opcode(opcodes_ptr, 0x62, "STP", STP, NONE_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0x63, "RRA", RRA, INDEXED_INDIRECT_X_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0x64, "NOP", NOP, ZEROPAGE_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0x65, "ADC", ADC_ptr, ZEROPAGE_ADDRESS_MODE, 3);
  set_opcode(opcodes_ptr, 0x66, "ROR", ROR, ZEROPAGE_ADDRESS_MODE, 5);
  set_opcode(opcodes_ptr, 0x67, "RRA", RRA, ZEROPAGE_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0x68, "PLA", PLA, NONE_ADDRESS_MODE, 4);
  set_opcode(opcodes_ptr, 0x69, "ADC", ADC_ptr, IMMEDIATE_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0x6a, "ROR", ROR, ACCUMULATOR_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0x6b, "ARR", ARR, IMMEDIATE_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0x6c, "JMP", JMP, ABSOLUTE_INDIRECT_ADDRESS_MODE, 5);
  set_opcode(opcodes_ptr, 0x6d, "ADC", ADC_ptr, ABSOLUTE_ADDRESS_MODE, 4);
  set_opcode(opcodes_ptr, 0x6e, "ROR", ROR, ABSOLUTE_ADDRESS_MODE, 6);
  set_opcode(opcodes_ptr, 0x6f, "RRA", RRA, ABSOLUTE_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0x70, "BVS", BVS, BRANCH_DUMMY, 2);
  set_opcode(opcodes_ptr, 0x71, "ADC", ADC_ptr, INDIRECT_INDEXED_Y_ADDRESS_MODE, 5);
  set_opcode(opcodes_ptr, 0x72, "STP", STP, NONE_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0x73, "RRA", RRA, INDIRECT_INDEXED_Y_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0x74, "NOP", NOP, ZEROPAGE_X_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0x75, "ADC", ADC_ptr, ZEROPAGE_X_ADDRESS_MODE, 4);
  set_opcode(opcodes_ptr, 0x76, "ROR", ROR, ZEROPAGE_X_ADDRESS_MODE, 6);
  set_opcode(opcodes_ptr, 0x77, "RRA", RRA, ZEROPAGE_X_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0x78, "SEI", SEI, NONE_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0x79, "ADC", ADC_ptr, ABSOLUTE_Y_ADDRESS_MODE, 4);
  set_opcode(opcodes_ptr, 0x7a, "NOP", NOP, NONE_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0x7b, "RRA", RRA, ABSOLUTE_Y_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0x7c, "NOP", NOP, ABSOLUTE_X_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0x7d, "ADC", ADC_ptr, ABSOLUTE_X_ADDRESS_MODE, 3);
  set_opcode(opcodes_ptr, 0x7e, "ROR", ROR, ABSOLUTE_X_ADDRESS_MODE, 7);
  set_opcode(opcodes_ptr, 0x7f, "RRA", RRA, ABSOLUTE_X_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0x80, "NOP", NOP, IMMEDIATE_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0x81, "STA", STA_ptr, INDEXED_INDIRECT_X_ADDRESS_MODE, 6);
  set_opcode(opcodes_ptr, 0x82, "NOP", NOP, IMMEDIATE_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0x83, "SAX", SAX, INDEXED_INDIRECT_X_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0x84, "STY", STY, ZEROPAGE_ADDRESS_MODE, 3);
  set_opcode(opcodes_ptr, 0x85, "STA", STA_ptr, ZEROPAGE_ADDRESS_MODE, 3);
  set_opcode(opcodes_ptr, 0x86, "STX", STX, ZEROPAGE_ADDRESS_MODE, 3);
  set_opcode(opcodes_ptr, 0x87, "SAX", SAX, ZEROPAGE_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0x88, "DEY", DEY, NONE_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0x89, "NOP", NOP, IMMEDIATE_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0x8a, "TXA", TXA, NONE_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0x8b, "XAA", XAA, IMMEDIATE_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0x8c, "STY", STY, ABSOLUTE_ADDRESS_MODE, 4);
  set_opcode(opcodes_ptr, 0x8d, "STA", STA_ptr, ABSOLUTE_ADDRESS_MODE, 4);
  set_opcode(opcodes_ptr, 0x8e, "STX", STX, ABSOLUTE_ADDRESS_MODE, 4);
  set_opcode(opcodes_ptr, 0x8f, "SAX", SAX, ABSOLUTE_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0x90, "BCC", BCC, BRANCH_DUMMY, 2);
  set_opcode(opcodes_ptr, 0x91, "STA", STA_ptr, INDIRECT_INDEXED_Y_ADDRESS_MODE, 6);
  set_opcode(opcodes_ptr, 0x92, "STP", STP, NONE_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0x93, "AHX", AHX, INDIRECT_INDEXED_Y_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0x94, "STY", STY, ZEROPAGE_X_ADDRESS_MODE, 4);
  set_opcode(opcodes_ptr, 0x95, "STA", STA_ptr, ZEROPAGE_X_ADDRESS_MODE, 4);
  set_opcode(opcodes_ptr, 0x96, "STX", STX, ZEROPAGE_Y_ADDRESS_MODE, 4);
  set_opcode(opcodes_ptr, 0x97, "SAX", SAX, ZEROPAGE_Y_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0x98, "TYA", TYA, NONE_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0x99, "STA", STA_ptr, ABSOLUTE_Y_ADDRESS_MODE, 5);
  set_opcode(opcodes_ptr, 0x9a, "TXS", TXS, NONE_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0x9b, "TAS", TAS, ABSOLUTE_Y_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0x9c, "SHY", SHY, ABSOLUTE_X_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0x9d, "STA", STA_ptr, ABSOLUTE_X_ADDRESS_MODE, 5);
  set_opcode(opcodes_ptr, 0x9e, "SHX", SHX, ABSOLUTE_Y_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0x9f, "AHX", AHX, ABSOLUTE_Y_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0xa0, "LDY", LDY, IMMEDIATE_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0xa1, "LDA", LDA_ptr, INDEXED_INDIRECT_X_ADDRESS_MODE, 6);
  set_opcode(opcodes_ptr, 0xa2, "LDX", LDX, IMMEDIATE_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0xa3, "LAX", LAX, INDEXED_INDIRECT_X_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0xa4, "LDY", LDY, ZEROPAGE_ADDRESS_MODE, 3);
  set_opcode(opcodes_ptr, 0xa5, "LDA", LDA_ptr, ZEROPAGE_ADDRESS_MODE, 3);
  set_opcode(opcodes_ptr, 0xa6, "LDX", LDX, ZEROPAGE_ADDRESS_MODE, 3);
  set_opcode(opcodes_ptr, 0xa7, "LAX", LAX, ZEROPAGE_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0xa8, "TAY", TAY, NONE_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0xa9, "LDA", LDA_ptr, IMMEDIATE_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0xaa, "TAX", TAX, NONE_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0xab, "LAX", LAX, IMMEDIATE_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0xac, "LDY", LDY, ABSOLUTE_ADDRESS_MODE, 4);
  set_opcode(opcodes_ptr, 0xad, "LDA", LDA_ptr, ABSOLUTE_ADDRESS_MODE, 4);
  set_opcode(opcodes_ptr, 0xae, "LDX", LDX, ABSOLUTE_ADDRESS_MODE, 4);
  set_opcode(opcodes_ptr, 0xaf, "LAX", LAX, ABSOLUTE_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0xb0, "BCS", BCS, BRANCH_DUMMY, 2);
  set_opcode(opcodes_ptr, 0xb1, "LDA", LDA_ptr, INDIRECT_INDEXED_Y_ADDRESS_MODE, 5);
  set_opcode(opcodes_ptr, 0xb2, "STP", STP, NONE_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0xb3, "LAX", LAX, INDIRECT_INDEXED_Y_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0xb4, "LDY", LDY, ZEROPAGE_X_ADDRESS_MODE, 4);
  set_opcode(opcodes_ptr, 0xb5, "LDA", LDA_ptr, ZEROPAGE_X_ADDRESS_MODE, 4);
  set_opcode(opcodes_ptr, 0xb6, "LDX", LDX, ZEROPAGE_Y_ADDRESS_MODE, 4);
  set_opcode(opcodes_ptr, 0xb7, "LAX", LAX, ZEROPAGE_Y_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0xb8, "CLV", CLV, NONE_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0xb9, "LDA", LDA_ptr, ABSOLUTE_Y_ADDRESS_MODE, 4);
  set_opcode(opcodes_ptr, 0xba, "TSX", TSX, NONE_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0xbb, "LAS", LAS, ABSOLUTE_Y_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0xbc, "LDY", LDY, ABSOLUTE_X_ADDRESS_MODE, 3);
  set_opcode(opcodes_ptr, 0xbd, "LDA", LDA_ptr, ABSOLUTE_X_ADDRESS_MODE, 4);
  set_opcode(opcodes_ptr, 0xbe, "LDX", LDX, ABSOLUTE_Y_ADDRESS_MODE, 4);
  set_opcode(opcodes_ptr, 0xbf, "LAX", LAX, ABSOLUTE_Y_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0xc0, "CPY", CPY, IMMEDIATE_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0xc1, "CMP", CMP, INDEXED_INDIRECT_X_ADDRESS_MODE, 6);
  set_opcode(opcodes_ptr, 0xc2, "NOP", NOP, IMMEDIATE_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0xc3, "DCP", DCP, INDEXED_INDIRECT_X_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0xc4, "CPY", CPY, ZEROPAGE_ADDRESS_MODE, 3);
  set_opcode(opcodes_ptr, 0xc5, "CMP", CMP, ZEROPAGE_ADDRESS_MODE, 3);
  set_opcode(opcodes_ptr, 0xc6, "DEC", DEC, ZEROPAGE_ADDRESS_MODE, 5);
  set_opcode(opcodes_ptr, 0xc7, "DCP", DCP, ZEROPAGE_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0xc8, "INY", INY, NONE_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0xc9, "CMP", CMP, IMMEDIATE_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0xca, "DEX", DEX, NONE_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0xcb, "AXS", AXS, IMMEDIATE_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0xcc, "CPY", CPY, ABSOLUTE_ADDRESS_MODE, 4);
  set_opcode(opcodes_ptr, 0xcd, "CMP", CMP, ABSOLUTE_ADDRESS_MODE, 4);
  set_opcode(opcodes_ptr, 0xce, "DEC", DEC, ABSOLUTE_ADDRESS_MODE, 6);
  set_opcode(opcodes_ptr, 0xcf, "DCP", DCP, ABSOLUTE_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0xd0, "BNE", BNE, BRANCH_DUMMY, 2);
  set_opcode(opcodes_ptr, 0xd1, "CMP", CMP, INDIRECT_INDEXED_Y_ADDRESS_MODE, 5);
  set_opcode(opcodes_ptr, 0xd2, "STP", STP, NONE_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0xd3, "DCP", DCP, INDIRECT_INDEXED_Y_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0xd4, "NOP", NOP, ZEROPAGE_X_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0xd5, "CMP", CMP, ZEROPAGE_X_ADDRESS_MODE, 4);
  set_opcode(opcodes_ptr, 0xd6, "DEC", DEC, ZEROPAGE_X_ADDRESS_MODE, 6);
  set_opcode(opcodes_ptr, 0xd7, "DCP", DCP, ZEROPAGE_X_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0xd8, "CLD", CLD, NONE_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0xd9, "CMP", CMP, ABSOLUTE_Y_ADDRESS_MODE, 4);
  set_opcode(opcodes_ptr, 0xda, "NOP", NOP, NONE_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0xdb, "DCP", DCP, ABSOLUTE_Y_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0xdc, "NOP", NOP, ABSOLUTE_X_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0xdd, "CMP", CMP, ABSOLUTE_X_ADDRESS_MODE, 4);
  set_opcode(opcodes_ptr, 0xde, "DEC", DEC, ABSOLUTE_X_ADDRESS_MODE, 7);
  set_opcode(opcodes_ptr, 0xdf, "DCP", DCP, ABSOLUTE_X_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0xe0, "CPX", CPX, IMMEDIATE_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0xe1, "SBC", SBC_ptr, INDEXED_INDIRECT_X_ADDRESS_MODE, 6);
  set_opcode(opcodes_ptr, 0xe2, "NOP", NOP, IMMEDIATE_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0xe3, "ISB", ISC, INDEXED_INDIRECT_X_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0xe4, "CPX", CPX, ZEROPAGE_ADDRESS_MODE, 3);
  set_opcode(opcodes_ptr, 0xe5, "SBC", SBC_ptr, ZEROPAGE_ADDRESS_MODE, 3);
  set_opcode(opcodes_ptr, 0xe6, "INC", INC, ZEROPAGE_ADDRESS_MODE, 5);
  set_opcode(opcodes_ptr, 0xe7, "ISB", ISC, ZEROPAGE_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0xe8, "INX", INX, NONE_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0xe9, "SBC", SBC_ptr, IMMEDIATE_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0xea, "NOP", NOP, NONE_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0xeb, "SBC", SBC_ptr, IMMEDIATE_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0xec, "CPX", CPX, ABSOLUTE_ADDRESS_MODE, 4);
  set_opcode(opcodes_ptr, 0xed, "SBC", SBC_ptr, ABSOLUTE_ADDRESS_MODE, 4);
  set_opcode(opcodes_ptr, 0xee, "INC", INC, ABSOLUTE_ADDRESS_MODE, 6);
  set_opcode(opcodes_ptr, 0xef, "ISB", ISC, ABSOLUTE_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0xf0, "BEQ", BEQ, BRANCH_DUMMY, 2);
  set_opcode(opcodes_ptr, 0xf1, "SBC", SBC_ptr, INDIRECT_INDEXED_Y_ADDRESS_MODE, 5);
  set_opcode(opcodes_ptr, 0xf2, "STP", STP, NONE_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0xf3, "ISB", ISC, INDIRECT_INDEXED_Y_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0xf4, "NOP", NOP, ZEROPAGE_X_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0xf5, "SBC", SBC_ptr, ZEROPAGE_X_ADDRESS_MODE, 4);
  set_opcode(opcodes_ptr, 0xf6, "INC", INC, ZEROPAGE_X_ADDRESS_MODE, 6);
  set_opcode(opcodes_ptr, 0xf7, "ISB", ISC, ZEROPAGE_X_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0xf8, "SED", SED, NONE_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0xf9, "SBC", SBC_ptr, ABSOLUTE_Y_ADDRESS_MODE, 4);
  set_opcode(opcodes_ptr, 0xfa, "NOP", NOP, NONE_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0xfb, "ISB", ISC, ABSOLUTE_Y_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0xfc, "NOP", NOP, ABSOLUTE_X_ADDRESS_MODE, 2);
  set_opcode(opcodes_ptr, 0xfd, "SBC", SBC_ptr, ABSOLUTE_X_ADDRESS_MODE, 4);
  set_opcode(opcodes_ptr, 0xfe, "INC", INC, ABSOLUTE_X_ADDRESS_MODE, 7);
  set_opcode(opcodes_ptr, 0xff, "ISB", ISC, ABSOLUTE_X_ADDRESS_MODE, 2);

}

